dist: xenial
cache: pip
branches:
  only:
  - master
  - develop
  # https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
  # safe list can prevent tag building, add rexp to detect tag
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

language: python
python:
- 3.6
- 3.7

install:
- python setup.py -q install

script:
- make protoc
- python setup.py -q test

deploy:
  provider: pypi
  user: tonyyang
  password:
    # secure token: `echo -n "password" | travis encrypt --add deploy.password -r sql-machine-learning/pysqlflow`
    secure: u8hoMuMukUcD6D+y+61w93yczgcixTgj8wQadv0VrI7aEsIOkMi508FXhsj4gmgN95O7fUApi6oXWhmOllVGFy2wJ+zZH1M8WDZi6Gq23meWTs7K+f9m6dADN0+/Y87Nc/UIOQLO8bU38hqophDRbC5Utn5bY5/lkMZzg8ypG9luZ+div+6DmZ3+kxh8o7jByiql0JjBeVLfycVW+LUpu6Fqx0XIp+tyWx99osT9LxDoZyPOmN4yXiyhEWNaK9BHi2X+qxxymjZvEJ0nSKeyQmfxBoKFW0PXh1t6r2yP5h1FzeuvZ3jB4hyvYAplKJbWJ6RLNISpBitB4PeeIVTFBPEzjc5gtDPvc5oy/OoLtmtbxGpAYh/J+DOA5T9S3vfM38xLByGMgA/Tpj0521RVd/UeyLgOrw7yPR1ZdyfDILoJ+TdupSNBpF5uMemuQGoGprGuMMHhZC+9Yv3+pUitnugDBHCx/A5uWSh699fv7UQBH0AgG5tFroQLZO6M1UVWyhkY1+LJZTuW8N4Xgq3d5dh6KdTaAJ7HZrAjow1Vc9U0S6RlWyhRgnuDwcVs3O2sPjufRSo1NK+P8Y78Gy10L1vtIr8MJRtTkTqcztrBZWAwjcvCHlgNfOPpPW1wR6klfBYN2/0MFFUYlo2ZTbsQSIgSLcVvR9d+TZkWaCsImPg=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    repo: sql-machine-learning/pysqlflow
