dist: xenial
cache: pip
branches:
  only:
  - master
  - develop
  # https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
  # safe list can prevent tag building, add rexp to detect tag
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8-dev

install:
- python setup.py -q install

script:
- make protoc
- python setup.py -q test

before_deploy:
- make protoc

deploy:
  provider: pypi
  user: tonyyang
  password:
    # secure token: `echo -n "password" | travis encrypt --add deploy.password -r wangkuiyi/pysqlflow`
    secure: sDAa83Ty6gY5VEcGX8vZcy6poyHod2TUnZ9XQ/Bc8n9o5Zm1b7om6tvo8rJ5AyokDcWmXCTj8wqP4wcajnvzRee25dOfjZync23h+lrO23ovH7omSwmbjzaDIQa8OjlUz9AckI7GcW8h1Q9ARmr4vSBrGmk6qj0OADVNcsRRa7899ICArqI3PAfLj8zgu6Z2fvAcyzUi/Fmal4kOn/gjiB6Kpid2AxuWysyGe/lqxdIYfPmWCOKko68pkwcI+NJZoIZaK+C4Ahpv3SvKlvPBS9/JxTsKXy7zKbBrLQfqSGHRX06sciHtDD9BxY0kQmh0CezvZvl+inqodoTL6gS7QfEt4pdagKb2vYvJrDNdyZNJSyuI357oTMGpS4bOCfxl5iQY73MttZXnC8OqmMJAWOcMhwMIayKjJJPALkCVyi5bHeqORepMIAx4QvAb/N1IObe+ltUCkmofSqxk0g26V6xcVB/ECfdjwPWY0h76MhCC+VkncuGImRcGaUQ4j/tnKDN2wDnst4WFs9xZf4Jq55gQyz+6loxU3Nhj3TzOpl8vFC92ozqfz4THjiymxstJfff0UidGQrP6rmWFTJFf5TePFdqVwkEVTs/tasetVP9aFL4ixR89A1uHQEL/n3Eby6AyD6ODIP0qTIkLadPe8yNrT9Qvg2FFRPOAbMmQyDk=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    repo: wangkuiyi/pysqlflow
